Upgrade actions/checkout to v4.0.0 (#887)
Sometimes we had the following issue in our CI

```
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@f43a0e5ff2bd294095638e[18](https://github.com/SharezoneApp/sharezone-app/actions/runs/6081692757/job/16497871915?pr=883#step:1:22)286ca9a3d[19](https://github.com/SharezoneApp/sharezone-app/actions/runs/6081692757/job/16497871915?pr=883#step:1:23)56744' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_cbdafda6-2c5b-4638-b6be-e6d65c6e3a8a/4afea807-b012-4842-986f-87c77b76bc37.tar.gz. return code: 2.
```

This is the issue: https://github.com/actions/checkout/issues/1448.
Upgrading to 4.0.0 should fix the issue (see
https://github.com/actions/checkout/issues/1448#issuecomment-1705296071)