Trim the "What's new" string when publishing a new version to TestFlight (#435)
Sometimes our updates for TestFlight because of:

```
PATCH https://api.appstoreconnect.apple.com/v1/betaBuildLocalizations/6206a1b0-01b6-4285-976b-b795f6aaf60c returned 409: An attribute value has invalid text. - Text for whatsNew contains invalid characters/formats.
Failed to publish build/ios/ipa/sharezone.ipa
Error: Process completed with exit code 1.
```

I assume that this is because of the whitespace at the end (see #422).
Therefore, we are trimming now the "What's new" string when pushing to
TestFlight.

Closes #422