Add `--export-options-plist` to `sz deploy ios` and `sz build ios` (#709)
Required to fix the signing issue:

> error: exportArchive: "Runner.app" requires a provisioning profile
with the Associated Domains, Push Notifications, and Sign in with Apple
features.

Tested it in
https://github.com/SharezoneApp/sharezone-app/actions/runs/5777294265/job/15657309237.